name: release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write  

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'frostybee' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm i

      - uses: changesets/action@v1
        with:
          version: pnpm run ci-version
          publish: pnpm run ci-publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
        
